### ISSUE TITLE
After I start it and make the adjustments / crash

### ISSUE THREAD

**Issue by banshek7** [OiwexO/PoolPredictor#1]
After I start and make the adjustments, and hit save twice, the whole thing just crashes, do you know why?

**Comment by banshek7** [comment]
Nvm, sorry I fixed it, but when I turn draw lines on it just spams tons of lines around in a circle, cool project though man, ty!

**Comment by OiwexO** [comment]
What you see is debug mode. If you build release apk, decompile it and inject libraries and smali code into 8 ball pool 5.8.0 32-bit apk it will work like this:
![predictor.jpg](https://github.com/OiwexO/PoolPredictor/assets/134169545/e2c7c81c-628c-4ac1-ae6e-9a591e6c4766)

I'll write a README with instructions when I have time

**Comment by banshek7** [comment]
lmfao bro thats fucking sick. I feel mentally handicapped that I dont know what you mean by this fully 

. If you build release apk, decompile it and inject libraries and smali code

And I dont want to harass you, i can understand the release apk part, but decompile it (Did you mean compile?) inject libraries and smali code?  I'm guessing those result from decompiling, but i dont have any kind of injector, this is my first time using android studio, i randomly found your project rofl.

**Comment by banshek7** [comment]
Please note if you decided to help me, I've already started working with A.I to understand all the steps i need to do. So I'm trying bro, thank you!    I'm "keanupwnu"  on discord. You can have my triggerbot / no recoil project pixel based im working on for apex if you want, it can target w/e list of hexes you give it, but im targeting a P2C apex glow magenta color.

**Comment by OiwexO** [comment]
I just uploaded a readme with all steps explained. Hope this helps

**Comment by banshek7** [comment]
Sick bro, tremendous thank you, I had that nigerian scam artist 60 dollar a month thing for a month ages ago when it first came out for game loop and I'd love to play some predicted pockets again

**Comment by banshek7** [comment]
Lmfao... bro if i you didnt put that readme id be in the fucking twilight zone, I was assuming I was going to get apktool, figure out what files i need, then scan the internet for some apk injector and inject multiple files. So thanks again<3
