### ISSUE TITLE
Problem embedding the mod in the game

### ISSUE THREAD

**Issue by hhhhteste001** [OiwexO/PoolPredictor#2]
There is something wrong in the explanation for assembling the mod because I am not able to embed the mod in the game with your explanation, (Copy iwex folder from predictor\smali\com to pool\smali_classes4\com\.) In this part you don't explain which smali is to copy from the mod, because the 9 smali folders, then pool\smali_classes4\com\ in that smali_classes4 there is no *com* folder. If possible, record a short video showing how to embed the mod in the game please.

**Comment by OiwexO** [comment]
Read readme carefully. You should build release apk (step 2). Then there will be only one smali folder. Also if there is no com folder, just create it.
