### ISSUE TITLE
theres a problem in the app after compiling it

### ISSUE THREAD

**Issue by Justinnilscoding** [OiwexO/PoolPredictor#4]
So I've done all the step,  step 1-3, step 7 and 9, are really confusing

**Comment by OiwexO** [comment]
Please provide more details about the problem

**Comment by putyinoajs** [comment]
Would i be able to get the 8 ball pool from the apk mirror? it doesn't work anymore

**Comment by OiwexO** [comment]
> it doesn't work anymore

The link works I just checked it. Just scroll down and there'll be a Download apk button

**Comment by putyinoajs** [comment]
thankyou ill check it

**Comment by putyinoajs** [comment]
it was showing expired so i thought it wasn't working anymore xd, i wanna ask  if putting the other code in the one im making would make it work?

**Comment by putyinoajs** [comment]
could you do a quick video tutorial? Im new at doing codes and stuff

**Comment by OiwexO** [comment]
> i wanna ask if putting the other code in the one im making would make it work?

I have no idea, it all depends on the code you write.
